using System;
using Greedy = Scheduling_Library.SchedulerSolverGreedy;

namespace Scheduling_Library
{
    public class Schedule
    {
        public static void Main(string[] args)
        {
            Greedy solver = new Greedy();
            Console.WriteLine("Please enter the filepath for the employee availability file.  This file would have been generated by the scraper script.");
            solver.AssignShifts(Console.ReadLine());
            Console.WriteLine(solver);
        }
    }
}